# Generated by Django 5.1.4 on 2026-07-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='confidence',
            new_name='top_confidence',
        ),
        migrations.RemoveField(
            model_name='observation',
            name='image_url',
        ),
        migrations.AddField(
            model_name='observation',
            name='image_storage_key',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
