# Generated by Django 5.1.4 on 2026-07-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('common_name', models.CharField(max_length=255)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('habitat', models.TextField(blank=True, null=True)),
                ('diet', models.TextField(blank=True, null=True)),
                ('max_size_cm', models.FloatField(blank=True, null=True)),
                ('conservation_status', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('fun_fact', models.TextField(blank=True, null=True)),
                ('north_american_freshwater', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
    ]
